### ISSUE TITLE
the latest version for gdb

### ISSUE THREAD

**Issue by hezhiye** [hugsy/gdb-static#6]
hi:  
   thanks for the sharing for gdb-static, it is really useful for me.
   do we have the plan for the latest version for gdb like gdb-11.2 or newer ?

**Comment by hugsy** [comment]
I've not planned to do so, but I'd take PRs

**Comment by hezhiye** [comment]
ok, can you show the steps or the guilder link for build statically for gdb not gdbserver ? I want to try the latest version for gdb
